ServerEvents.commandRegistry(event => {
    const { commands: Commands, arguments: Arguments } = event
    event.register(Commands.literal("sg")
        .requires(s => s.hasPermission(2))
        .then(Commands.literal(`chests`).requires(source => source.hasPermission(2))
            .then(Commands.literal('create').executes(c => createChestMakingTools(c.source.player)))
            .then(Commands.literal('highlight')
                .then(Commands.argument('bool', Arguments.BOOLEAN.create(event))
                    .executes(c => highlightEveryChest(c.source.level, Arguments.BOOLEAN.getResult(c, 'bool')))
                )
            )
        )
        .then(Commands.literal(`spawn`).requires(source => source.hasPermission(2))
            .then(Commands.literal('add').executes(c => createPlayerSpawn(c.source.player)))
            .then(Commands.literal('remove').executes(c => removePlayerSpawn(c.source.player)))
        )
        .then(Commands.literal(`join`).requires(source => source.hasPermission(0))
            .executes(c => joinLobby(c.source.player, c.source.server))
        )
        .then(Commands.literal(`vote`).requires(source => source.hasPermission(0))
            .executes(c => playerVote(c.source.player, c.source.server))
        )
        .then(Commands.literal(`unvote`).requires(source => source.hasPermission(0))
            .executes(c => playerUnvote(c.source.player, c.source.server))
        )
        .then(Commands.literal(`leave`).requires(source => source.hasPermission(0))
            .executes(c => leaveLobby(c.source.player, c.source.server))
        )
        .then(Commands.literal(`stop`).requires(source => source.hasPermission(2))
        .executes(c => stopGame(c.source.server, c.source.level))
        )
        .then(Commands.literal(`start`).requires(source => source.hasPermission(2))
            .executes(c => startGame(c.source.server, c.source.level))
        )
    )

    //TODO
    /*event.register(Commands.literal("survivalgames")
        .requires(s => s.hasPermission(2))
        .then(Commands.literal(`chests`).requires(source => source.hasPermission(2))
            .executes(c => createChestMakingTools(c.source.player))
        )
        .then(Commands.literal(`join`).requires(source => source.hasPermission(0))

        )
        .then(Commands.literal(`leave`).requires(source => source.hasPermission(0))

        )
        .then(Commands.literal(`stop`).requires(source => source.hasPermission(2))

        )

    )*/
})